### ISSUE TITLE
kind cluster connection refused

### ISSUE THREAD

**Issue by ougabriel** [ougabriel/Deploy-a-tetris-Java-Application-on-Kubernetes-hosted-on-AWS-using-GitActions2#3]
To modify the KinD (Kubernetes in Docker) configuration to allow remote access to the API server, I added extra port mappings to the control-plane node in the existing `kind-config.yaml` file. 

### Step 1: Update the KinD Configuration File

delete the existing cluster

```bash
kubectl delete cluster
```

Add port mappings to the control-plane node to expose the API server on the host machine.

**Updated `kind-config.yaml`:**

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 6443
    hostPort: 6443
    listenAddress: "0.0.0.0"
    protocol: TCP
  kubeadmConfigPatches:
  - |
    apiServer:
      extraArgs:
        advertise-address: "35.172.236.137"
        bind-address: "0.0.0.0"
        tls-san: "35.172.236.137"
- role: worker

```

This configuration maps port 6443 of the control-plane container to port 6443 on the host machine.

### Step 2: Create the KinD Cluster with the Updated Configuration

Create the KinD cluster using the updated configuration file:

```bash
kind create cluster --config kind-config.yaml
```

### Step 3: Configure Firewall and Networking

Ensure your host machine's firewall and any security groups allow incoming connections on port 6443.

**On Ubuntu:**

```bash
sudo ufw allow 6443/tcp
```

**For cloud-hosted VMs (e.g., AWS EC2, Google Cloud VM):**

Ensure that the security group associated with the VM allows inbound traffic on port 6443.

### Step 4: Update Kubeconfig for Remote Access

1. **Find the Host Machine's Public IP Address:**

   Use a service like `ifconfig.me` to get the public IP address of your host machine:

   ```bash
   curl ifconfig.me
   ```

2. **Modify kubeconfig:**

   Update the `server` field in your kubeconfig file to use the public IP address of your host machine.

   ```bash
   kubectl config set-cluster kind-kind --server=https://<YOUR-HOST-IP>:6443
   ```

   Replace `<YOUR-HOST-IP>` with the public IP address of your host machine.
like this
![image](https://github.com/ougabriel/Deploy-a-tetris-Java-Application-on-Kubernetes-hosted-on-AWS-using-GitActions2/assets/34310658/e09939e1-2997-4a19-adb9-554e8862bdc8)

### Step 5: Access the Kubernetes API Server Remotely

1. **Copy the Kubeconfig File:**

   Copy the updated kubeconfig file to the remote machine from where you want to access the KinD cluster.

2. **Use kubectl on Remote Machine:**

   Use `kubectl` on the remote machine with the updated kubeconfig to access the KinD cluster:

   ```bash
   KUBECONFIG=/path/to/updated/kubeconfig kubectl get nodes
   ```

### Example kubeconfig Update

If your original kubeconfig looks like this:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <CERTIFICATE>
    server: https://127.0.0.1:6443
  name: kind-kind
contexts:
- context:
    cluster: kind-kind
    user: kind-kind
  name: kind-kind
current-context: kind-kind
kind: Config
preferences: {}
users:
- name: kind-kind
  user:
    client-certificate-data: <CERTIFICATE>
    client-key-data: <KEY>
```

You need to update the `server` field:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <CERTIFICATE>
    server: https://<YOUR-HOST-IP>:6443
  name: kind-kind
contexts:
- context:
    cluster: kind-kind
    user: kind-kind
  name: kind-kind
current-context: kind-kind
kind: Config
preferences: {}
users:
- name: kind-kind
  user:
    client-certificate-data: <CERTIFICATE>
    client-key-data: <KEY>
```

### Summary

By following these steps, you should be able to access the KinD API server from a remote machine. Ensure that your network and security settings are properly configured to avoid unauthorized access.
